### ISSUE TITLE
Toast to update the mod shows when with an incompatible Minecraft version

### ISSUE THREAD

**Issue by osfanbuff63** [dvitski/companion#18]
The toast when you join MCCI to update MCCIC shows even when that version is incompatible with the version of Minecraft you are running.

**Steps to Reproduce**:
1. Download [MCCIC 4.0.0-beta.21-1.19](https://modrinth.com/mod/mccic/version/4.0.0-beta.21+1.19) and open a 1.19.2 instance with it.
2. Join MCC Island and notice that the toast in the top right shows to update MCCIC even though there isn't a newer version for 1.19.2 - only 1.19.3.

By the way, this is a great mod :heart:

**Comment by dvitski** [comment]
I'm not really sure what to do about this because MCCI: Companion will always support the latest version of Minecraft that MCC: Island also supports.

In the event that version compatibility was checked, 1.19.2 users would never be aware that MCCI: Companion has an update available as another 1.19.2 update will never exist.

*And thank you!*

**Comment by dvitski** [comment]
I hope to have remedied this a bit in beta 26 - I've made the update messages more descriptive and added configuration to disable the update notifications if you'd like in the toasts module
